INSERT INTO CURRENCY (ID, CUR, CURDESC, EXCHANGERATE) VALUES (1, 'USD', '美金', 28);
INSERT INTO CURRENCY (ID, CUR, CURDESC, EXCHANGERATE) VALUES (2, 'GBP', '英鎊', 37);
INSERT INTO CURRENCY (ID, CUR, CURDESC, EXCHANGERATE) VALUES (3, 'EUR', '歐元', 31);
