DROP TABLE IF EXISTS CURRENCY;
CREATE TABLE CURRENCY (
      id INT AUTO_INCREMENT  PRIMARY KEY,
      cur VARCHAR(50) NOT NULL,
      curdesc VARCHAR(255) NOT NULL,
      exchangerate DECIMAL(10,3) NOT NULL,
);